name: CI-CD BetterYou

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Make mvnw executable
        working-directory: backend
        run: chmod +x mvnw

      - name: Backend tests
        working-directory: backend
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./mvnw clean test

      - name: Build backend
        working-directory: backend
        run: ./mvnw -q clean package -DskipTests


  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install & Build frontend
        run: |
          cd frontend
          npm install
          npm run build


  docker-build-push:
    runs-on: ubuntu-latest
    needs: [build-test-backend, build-frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Make mvnw executable
        working-directory: backend
        run: chmod +x mvnw

      - name: Build backend jar for Docker
        working-directory: backend
        run: ./mvnw -q clean package -DskipTests

      # üîÅ On reconstruit le frontend (pour ce que ton Dockerfile.frontend va copier)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

## üîÅ On reconstruit le frontend (pour ce que ton Dockerfile.frontend va copier) en injectant pour prod 
      - name: Build frontend for Docker
        run: |
          cd frontend
          npm install
          VITE_API_URL=https://betteryou-backend-rbly.onrender.com npm run build


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/betteryou-backend:latest -f devops/Dockerfile.backend .

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/betteryou-frontend:latest -f devops/Dockerfile.frontend .

      - name: Push images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/betteryou-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/betteryou-frontend:latest

      - name: Logout Docker
        run: docker logout
        
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [docker-build-push]
  #   steps:
  #     - name: Deploy on Oracle VM
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           cd ~/betteryou
  #           podman-compose pull
  #           podman-compose up -d
  #           podman image prune -f
  deploy-render:
    runs-on: ubuntu-latest
    needs: [docker-build-push]
    if: github.ref == 'refs/heads/main'  # ‚¨ÖÔ∏è AJOUTEZ CETTE LIGNE
    steps:
      - name: Trigger Render Backend Deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}"
      - name: Trigger Render Frontend Deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}"