name: CI-CD BetterYou

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # ðŸ”¹ Donne les droits d'exÃ©cution au script mvnw dans backend/
      - name: Make mvnw executable
        working-directory: backend
        run: chmod +x mvnw

      - name: Backend tests
        working-directory: backend
        run: ./mvnw clean test
      - name: Build backend
        working-directory: backend
        run: ./mvnw -q clean package -DskipTests


  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install & Build frontend
        run: |
          cd frontend
          npm install
          npm run build

  docker-build-push:
    runs-on: ubuntu-latest
    needs: [build-test-backend, build-frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/betteryou-backend:latest -f Dockerfile.backend .

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/betteryou-frontend:latest -f Dockerfile.frontend .

      - name: Push images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/betteryou-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/betteryou-frontend:latest
